new branch for cypress

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -665,6 +665,7 @@ orbs:
         # Runs user journey tests using casper JS
         #
         executor: python
+        resource_class: large
         parameters:
           workspace:
             description: Terraform workspace name
@@ -679,18 +680,24 @@ orbs:
               at: /tmp
           - dockerhub_login
           - run:
-              name: Build casper JS container
+              name: Build cypress container
               command: |
-                docker build -f ~/project/tests/Dockerfile  -t casperjs:latest .
-                echo 'export DOCKER_REMOTE_IP="$(docker run casperjs:latest curl --silent https://checkip.amazonaws.com/)"' >> $BASH_ENV
-                echo $DOCKER_REMOTE_IP
-          - run:
-              name: Build pa11y container
-              command: |
-                cd ~/project/tests/pa11y
-                docker build -t opgpa11y:latest .
-                echo 'export DOCKER_PA11Y_REMOTE_IP="$(docker run opgpa11y:latest curl --silent https://checkip.amazonaws.com/)"' >> $BASH_ENV
-                echo $DOCKER_PA11Y_REMOTE_IP
+                docker build -f ./cypress/Dockerfile  -t cypress:latest .
+                echo 'export DOCKER_CYPRESS_REMOTE_IP="$(docker run cypress:latest curl --silent https://checkip.amazonaws.com/)"' >> $BASH_ENV
+                echo $DOCKER_CYPRESS_REMOTE_IP
+                #- run:
+                #name: Build casper JS container
+                #command: |
+                #docker build -f ~/project/tests/Dockerfile  -t casperjs:latest .
+                #echo 'export DOCKER_REMOTE_IP="$(docker run casperjs:latest curl --silent https://checkip.amazonaws.com/)"' >> $BASH_ENV
+                #echo $DOCKER_REMOTE_IP
+                #- run:
+            #name: Build pa11y container
+            #  command: |
+            #    cd ~/project/tests/pa11y
+            #    docker build -t opgpa11y:latest .
+            #    echo 'export DOCKER_PA11Y_REMOTE_IP="$(docker run opgpa11y:latest curl --silent https://checkip.amazonaws.com/)"' >> $BASH_ENV
+            #    echo $DOCKER_PA11Y_REMOTE_IP
           - run:
               name: Install python dependencies
               command: |
@@ -719,16 +726,21 @@ orbs:
                   terraform apply -lock-timeout=300s -auto-approve -var docker_remote_ip=$DOCKER_REMOTE_IP
                 fi
           - run:
-              name: Run pa11y test
+              name: Run cypress tests
               command: |
-                docker run -dt -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN -e CI -e "BASE_DOMAIN=$FRONT_DOMAIN" --name opgpa11y opgpa11y:latest
-                docker exec opgpa11y sed -i "s/localhost:7002/$FRONT_DOMAIN/" config.json
-                docker exec opgpa11y pa11y-ci -c config.json || true # true prevents this being a failure if pa11y has errors. one day we will want to remove true
-          - run:
-              name: Run test
-              command: |
-                docker run -dt -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN -e CI -e "BASE_DOMAIN=$FRONT_DOMAIN" --name casperjs casperjs:latest
-                docker exec casperjs ./start.sh 'tests/'
+                docker run -dt -e "CYPRESS_baseUrl=$FRONT_DOMAIN" --ipc=host --shm-size=1024M --name opgcypress cypress:latest 
+                docker exec opgcypress cypress run --spec cypress/integration/basic_login.js
+                #- run:
+                #              name: Run pa11y tests
+                #              command: |
+                #docker run -dt -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN -e CI -e "BASE_DOMAIN=$FRONT_DOMAIN" --name opgpa11y opgpa11y:latest
+                #docker exec opgpa11y sed -i "s/localhost:7002/$FRONT_DOMAIN/" config.json
+                #docker exec opgpa11y pa11y-ci -c config.json || true # true prevents this being a failure if pa11y has errors. one day we will want to remove true
+                #- run:
+                #name: Run caspar tests
+                #command: |
+                #docker run -dt -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN -e CI -e "BASE_DOMAIN=$FRONT_DOMAIN" --name casperjs casperjs:latest
+                #docker exec casperjs ./start.sh 'tests/'
           - run:
               name: Remove CircleCI ingress to environment
               command: |
