define healthcheck jobs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -317,6 +317,38 @@ orbs:
                   echo $TF_WORKSPACE
                   terraform destroy -lock-timeout=300s -auto-approve
                 fi      
+      run_healthcheck_test:
+        #
+        # Checks the health check is returning 200
+        #
+        executor: python
+        parameters:
+          workspace:
+            description: Terraform workspace name
+            type: string
+            default: "${CIRCLE_PULL_REQUEST##*/}-${CIRCLE_BRANCH//[-_]/}"
+        steps:
+          - checkout
+          - install_webdriver
+          - attach_workspace:
+              at: /tmp
+          - run:
+              name: Wait for new tasks in services to be running
+              command: |
+                export TF_WORKSPACE=${ENV_NAME:0:13} >> $BASH_ENV
+                echo $TF_WORKSPACE              
+                sudo pip3 install boto3
+                python features/aws_ecs_task.py /tmp/cluster_config.json
+          - run:
+              name: Run test
+              command: |
+                front_fqdn=$(cat /tmp/environment_pipeline_tasks_config.json | jq .front_fqdn | xargs)
+                healthcheck_response=$(curl --write-out %{http_code} --silent --output /dev/null https://$front_fqdn/ping/json)
+                [[ $healthcheck_response == 200 ]] || (echo "Error with viewer health check. HTTP status: ${healthcheck_response}" && exit 1)
+
+
+
+
 jobs:
   slack_notify_domain:
     docker:
