add End of workflow

diff --git a/.github/workflows/workflow_merge_queue.yml b/.github/workflows/workflow_merge_queue.yml
--- a/.github/workflows/workflow_merge_queue.yml
+++ b/.github/workflows/workflow_merge_queue.yml
@@ -265,3 +265,38 @@ jobs:
       front_url: https://${{ needs.preprod_terraform_outputs.outputs.front_fqdn }}
       account_id: "987830934591"
     secrets: inherit #pragma: allowlist secret
+
+  end_of_workflow:
+    name: End of Workflow
+    runs-on: ubuntu-latest
+    needs:
+      - terraform_environment_preproduction
+      - preprod_terraform_outputs
+      - set_variables
+      - cypress_tests_Signup_StichedPF
+      - cypress_tests_Signup_StichedHW
+      - cypress_tests_SignupIncluded
+      - cypress_tests_Remaining
+    environment:
+      name: "preproduction"
+      url: "https://${{ env.FRONT_URL }}/home"
+    env:
+      FRONT_URL: ${{ needs.preprod_terraform_outputs.outputs.front_fqdn }}
+    steps:
+      - name: End of Workflow
+        run: |
+          if ${{ contains(needs.terraform_environment_preproduction.result, 'success')}} &&
+            ${{ contains(needs.preprod_terraform_outputs.result, 'success')}} &&
+            ${{ contains(needs.cypress_tests_Signup_StichedPF.result, 'success')}} &&
+            ${{ contains(needs.cypress_tests_Signup_StichedHW.result, 'success')}} &&
+            ${{ contains(needs.cypress_tests_SignupIncluded.result, 'success')}} &&
+            ${{ contains(needs.cypress_tests_Remaining.result, 'success')}}; then
+            echo "Preproduction environment tested, built and deployed"
+            echo "Tag Deployed: integration-${{ needs.set_variables.outputs.semver_tag }}"
+            echo "URL: https://${{ env.FRONT_URL }}/home"
+            exit 0
+          else
+            echo "Previous jobs in pipeline failed."
+            exit 1
+          fi
+    if: always()
